### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Manubi** [spa5k/monorepo-typescript-rust#3]
Hi! 
Thanks for the boilerplate. Do you also have somewhere a documentation which goes a little deeper into stuff?
Also about why you choose a certain technology?
Another question is how do you deploy it?
How is the dev workflow?
Thanks!

**Comment by spa5k** [comment]
The tech stack was rather random - 

Vite for SPA

NextJS for SSR

and Actix is quite famous web server in rust.


Coming to deployment, you can deploy them separately, just run the build command like 

```
pnpm athena build
````

it will build all the packages that are necessary, even if they are shared monorepo packages.
